
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Sep 15 17:11:54 GMT-06:00 2025
//----------------------------------------------------

package act4;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAR_DER = 61;
  public static final int SHORT = 10;
  public static final int CONST = 9;
  public static final int CHAR = 7;
  public static final int PUNTOYCOMA = 64;
  public static final int COMENTARIO_MULTI = 41;
  public static final int ENTERO = 36;
  public static final int DIFERENTE = 52;
  public static final int CASE = 24;
  public static final int RESTA = 43;
  public static final int DOUBLE = 8;
  public static final int CONTINUE = 27;
  public static final int INT = 2;
  public static final int COR_DER = 57;
  public static final int REGISTER = 14;
  public static final int FOR = 20;
  public static final int STATIC = 15;
  public static final int LLAVE_IZQ = 58;
  public static final int NOT = 55;
  public static final int AND = 53;
  public static final int MENORIGUAL = 49;
  public static final int IDENTIFICADOR = 35;
  public static final int YES = 33;
  public static final int IGUAL = 51;
  public static final int CARACTER = 39;
  public static final int OR = 54;
  public static final int SUMA = 42;
  public static final int EXTERN = 16;
  public static final int IF = 18;
  public static final int MAYORIGUAL = 50;
  public static final int EOF = 0;
  public static final int BOOLEAN = 6;
  public static final int RETURN = 29;
  public static final int TRUE = 31;
  public static final int error = 1;
  public static final int COMA = 62;
  public static final int CADENA = 38;
  public static final int MODULO = 46;
  public static final int COMENTARIO = 40;
  public static final int MENOR = 47;
  public static final int UNSIGNED = 12;
  public static final int AUTO = 13;
  public static final int PAR_IZQ = 60;
  public static final int BREAK = 26;
  public static final int VOID = 17;
  public static final int ASIGNACION = 65;
  public static final int SWITCH = 23;
  public static final int BYTE = 3;
  public static final int MAYOR = 48;
  public static final int IMPORT = 34;
  public static final int NO = 32;
  public static final int ELSE = 19;
  public static final int PUNTO = 63;
  public static final int LLAVE_DER = 59;
  public static final int SIGNED = 11;
  public static final int GOTO = 28;
  public static final int WHILE = 21;
  public static final int DEFAULT = 25;
  public static final int FLOAT = 5;
  public static final int COR_IZQ = 56;
  public static final int LONG = 4;
  public static final int FALSE = 30;
  public static final int DIVISION = 45;
  public static final int FLOTANTE = 37;
  public static final int DO = 22;
  public static final int MULTIPLICACION = 44;
}

